ASSISTANT_NAME = "Jarvis"
WAKE_MESSAGE = "Hey Dev Jravis is there"
EXIT_MESSAGE = "Bye Dev Call me when You need me"
WAKE_WORD = "jarvis"
EMAIL_USER = "charayadev11@gmail.com"
EMAIL_PASS = "cfli dshh pktd eltk"